version: '3.9'
services:
  readme.users.mongo:
    image: mongo:4.4
    restart: always
    container_name: readme.users.mongo

    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB_NAME}

    ports:
      - "${MONGO_PORT}:27017"

    volumes:
      - readme.mongo.users:/data/db # том
      # - "/c/database/readme/users.mongo/:/data/db/" # маппинг директорий

  readme.users.mongo.ui:
    image: mongo-express:1.0.2-20
    restart: always
    container_name: readme.users.mongo.ui

    environment:
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_USER}
      ME_CONFIG_BASICAUTH_PASSWORd: ${MONGO_PASSWORD}
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@readme.users.mongo:${MONGO_PORT}/

    ports:
      - "8081:8081"

volumes:
  readme.mongo.users:

